BMD-3396 Still not possible to make request on minedata.berlingskemedia.dk - GSP'en
BerlingskeMedia/nyhedsbreveprofil pull request #109
Opened 2020-09-01 13:25 UTC by qbanic

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-3396

2020-09-02 06:54 UTC, ruitra approved these changes

2020-09-02 06:54 UTC, ruitra commented on server/api_consumers/zendesk_client.js
> -    const validate_result = Joi.validate(ticket, createTicketSchema, { convert: false });
Ok this validation was removed?
Then `createTicketSchema` should also be removed?

2020-09-02 06:54 UTC, ruitra commented on mine-data/src/CategoryManualList/categoryManualList.actions.js
> +        dispatch(confirmAllowed(response));
Just to confirm, `confirmAllowed` should receive a response, yeah? Cause I see in its definition it expects allowed:
`export const confirmAllowed = allowed => ({
  type: CONFIRM_ALLOWED,
  allowed
});`

2020-09-02 09:29 UTC, qbanic commented on mine-data/src/CategoryManualList/categoryManualList.actions.js
> +        dispatch(confirmAllowed(response));
response is just a plain boolean true/false

2020-09-02 09:30 UTC, qbanic commented on server/api_consumers/zendesk_client.js
> -    const validate_result = Joi.validate(ticket, createTicketSchema, { convert: false });
Ive reworked joi validation, old structure was invalid, there is a new way to do it

2020-09-02 10:35 UTC, dgolabek-sii requested changes

2020-09-02 10:35 UTC, dgolabek-sii commented on server/api_consumers/zendesk_client.js
> -        }
why this is removed?

2020-09-02 10:36 UTC, bmxape approved these changes

2020-09-02 10:45 UTC, qbanic commented on server/api_consumers/zendesk_client.js
> -        }
KU (kundeunivers) is no longer supported in this project, aria replaced it. Besides, this fragment is responsible for blocking requests if there is already one created by user, but what if user has multiple different requests? I think its better to let user apply same req 2 times instead of disabling his ability for another, different request

2020-09-02 12:12 UTC, dgolabek-sii approved these changes

2020-09-07 09:14 UTC, dgolabek-sii approved these changes

2020-09-07 09:17 UTC, ruitra approved these changes

2020-09-07 09:40 UTC, bmxape approved these changes

2020-09-07 09:54 UTC, merged